from backend.models import Offer

SCORING_MODEL_VERSION = "rubric-v1"
SCORE_SCALE = 100

CAMPS_WEIGHT_REVENUE = 20
CAMPS_WEIGHT_ROSTER = 15
CAMPS_WEIGHT_LOW_EVENTS = 20
CAMPS_WEIGHT_ORG_TYPE = 15
CAMPS_WEIGHT_COACH_OR_ED = 15
CAMPS_WEIGHT_PROXIMITY = 15

CAMPS_REVENUE_THRESHOLD = 100_000
CAMPS_LARGE_ROSTER_MIN = 50
CAMPS_LOW_EVENTS_MAX = 4

CAMPS_YOUTH_OR_TRAVEL_TYPES = frozenset(
    {"youth_sports_org", "travel_program", "booster_club"}
)
CAMPS_COACH_OR_ED_ROLES = frozenset(
    {"head_coach", "assistant_coach", "executive_director"}
)

PANELS_WEIGHT_POLICY_EVENT = 35
PANELS_WEIGHT_COMPLIANCE_OFFICER = 20
PANELS_WEIGHT_SCHOOL_OR_COLLEGE = 15
PANELS_WEIGHT_INSTITUTION_SIZE = 15
PANELS_WEIGHT_NO_PRIOR_CONTACT = 15

PANELS_POLICY_RECENT_DAYS = 180
PANELS_INSTITUTION_SIZE_MIN = 500
PANELS_SCHOOL_OR_COLLEGE_TYPES = frozenset({"school_district", "college"})
PANELS_COMPLIANCE_ROLES = frozenset({"compliance_officer"})

MEDIA_WEIGHT_SPONSORS = 25
MEDIA_WEIGHT_SPONSOR_LOCATIONS = 15
MEDIA_WEIGHT_REVENUE = 20
MEDIA_WEIGHT_AUDIENCE = 20
MEDIA_WEIGHT_MARKETING_CONTACT = 20

MEDIA_REVENUE_THRESHOLD = 100_000
MEDIA_AUDIENCE_REVIEW_MIN = 25
MEDIA_SPONSOR_MULTI_LOCATION_MIN = 2
MEDIA_MARKETING_ROLES = frozenset({"marketing_contact"})

CAMPS_RUBRIC: dict[str, int] = {
    "revenue": CAMPS_WEIGHT_REVENUE,
    "roster": CAMPS_WEIGHT_ROSTER,
    "low_events": CAMPS_WEIGHT_LOW_EVENTS,
    "org_type": CAMPS_WEIGHT_ORG_TYPE,
    "coach_or_ed": CAMPS_WEIGHT_COACH_OR_ED,
    "proximity": CAMPS_WEIGHT_PROXIMITY,
}

PANELS_RUBRIC: dict[str, int] = {
    "policy_event": PANELS_WEIGHT_POLICY_EVENT,
    "compliance_officer": PANELS_WEIGHT_COMPLIANCE_OFFICER,
    "school_or_college": PANELS_WEIGHT_SCHOOL_OR_COLLEGE,
    "institution_size": PANELS_WEIGHT_INSTITUTION_SIZE,
    "no_prior_contact": PANELS_WEIGHT_NO_PRIOR_CONTACT,
}

MEDIA_RUBRIC: dict[str, int] = {
    "sponsors": MEDIA_WEIGHT_SPONSORS,
    "sponsor_locations": MEDIA_WEIGHT_SPONSOR_LOCATIONS,
    "revenue": MEDIA_WEIGHT_REVENUE,
    "audience": MEDIA_WEIGHT_AUDIENCE,
    "marketing_contact": MEDIA_WEIGHT_MARKETING_CONTACT,
}

RUBRICS: dict[Offer, dict[str, int]] = {
    Offer.camps: CAMPS_RUBRIC,
    Offer.panels: PANELS_RUBRIC,
    Offer.media: MEDIA_RUBRIC,
}
